apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-app-reloader
  labels:
    app: demo-app-reloader
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "demo-app-reloader"
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              args: ["rollout", "restart", "deployment/demo-app"]