apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "demo-app-reloader"
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    resourceNames:
      - "demo-app"
    verbs:
      - get
      - patch