apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "demo-app-reloader"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "demo-app-reloader"
subjects:
  - kind: ServiceAccount
    name: "demo-app-reloader"
